name = "jumarf"
compatibility_date = "2024-01-01"

[env.production]
name = "jumarf"
routes = [
  { pattern = "jumarf.fun/*", zone_name = "jumarf.fun" },
  { pattern = "jumarf.ru/*", zone_name = "jumarf.ru" }
]

[env.production.vars]
ENVIRONMENT = "production"
